name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Ruff format and lint
        run: |
          python -m ruff format --check .
          python -m ruff check .
      - name: Run tests with coverage
        run: |
          pytest --testmon --cov=. --cov-report=xml
      - name: Diff coverage
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          diff-cover coverage.xml --compare-branch origin/${{ github.event.pull_request.base.ref }} --fail-under=90
